### ISSUE TITLE
Multiple buttons codes

### ISSUE THREAD

**Issue by tatunts** [dimagoltsman/Random-Broadlink-RM-Code-Generator#1]
Hello @dimagoltsman!

First of all, great work on your code!

I would like to suggest something, if possible: most RF controllers nowadays have more than one button. Is it possible to generate one code with button 1, 2, 3, 4 and so on?

It would help with on/off switches, curtain motors (up, down and stop commands) and many others.

Also, it would be nice to know the chip this code is compatible (I believe that you read my conversation with Epsylon hehe) since there are some specifics about it.

I am sorry I cannot code and had not got the time to test your codes on my relays. I will do ASAP so I can help you somehow.

Thank you very much and again, great work here!

**Comment by dimagoltsman** [comment]
i dont really understand, what do u mean generate code with button?

**Comment by tatunts** [comment]
I believe that a controller with multiple buttons like this: [https://ae01.alicdn.com/kf/HTB1_JjFKXXXXXa9XpXXq6xXFXXXE/433mhz-RF-Remote-Control-Copy-code-4-channel-Remote-Electric-cloning-duplicator-433-mhz-Key-Fob.jpg_640x640.jpg](url) uses the same code to send 4 different commands, right?

I don't really now how it works tough but I have a few 433 RF relays that I pair with this controller with a generated code and both buttons 1 and 2 works as ON/OFF separated commands...

**Comment by dimagoltsman** [comment]
you mean that you want to get the code for broadlink from this remote?

**Comment by tatunts** [comment]
No sorry... My suggestion is that, since you've created a RF code generator, some devices requires more than one button to work but the generated RF code has a pattern that identifies separated buttons.

On my conversation with Epsylon, he always send me ON_COMMAND and OFF_COMMAND, like this:
```
# 0x064133 = 0000 0110 0100 0001 0011 0011: low_period=0x06, high_period=0x14, stop_period=0xbf, inverted?Y, TX mode=0xb2 433mhz
  command_on:  "sgCTAAYUBhQGFAYUBhQUBhQGBhQGFBQGBhQGFAYUBhQGFBQGBhQGFBQGFAYGFAYUFAYUBr8GFAYUBhQGFAYUFAYUBgYUBhQUBgYUBhQGFAYUBhQUBgYUBhQUBhQGBhQGFBQGFAa/BhQGFAYUBhQGFBQGFAYGFAYUFAYGFAYUBhQGFAYUFAYGFAYUFAYUBgYUBhQUBhQGvw=="
# 0x06413c = 0000 0110 0100 0001 0011 1100: low_period=0x06, high_period=0x14, stop_period=0xbf, inverted?Y, TX mode=0xb2 433mhz
  command_off: "sgCTAAYUBhQGFAYUBhQUBhQGBhQGFBQGBhQGFAYUBhQGFBQGBhQGFBQGFAYUBhQGBhQGFL8GFAYUBhQGFAYUFAYUBgYUBhQUBgYUBhQGFAYUBhQUBgYUBhQUBhQGFAYUBgYUBhS/BhQGFAYUBhQGFBQGFAYGFAYUFAYGFAYUBhQGFAYUFAYGFAYUFAYUBhQGFAYGFAYUvw=="
```
So if I pair the ON_COMMAND with the relay, the OFF_COMMAND also works with it. I have no idea why hehe

Sorry if I cannot explain myself correctly... English is not my mother language :)

**Comment by dimagoltsman** [comment]
thats because your receiver probably work only with one code that changes the state. you should see if your device can work for separated codes

**Comment by dimagoltsman** [comment]
👍
