### ISSUE TITLE
Question about HEX

### ISSUE THREAD

**Issue by matrosovas** [dimagoltsman/Random-Broadlink-RM-Code-Generator#3]
Hello,
I want to switch all my light switches to livolo ones and I have a question before I go ahead and buy them without remotes. The code that you generate, can it somehow be used as a HEX in this plugin? https://github.com/lprhodes/homebridge-broadlink-rm

**Comment by amatrosovas** [comment]
@dimagoltsman forgot to mention you when creating this :) Thanks for your time.

**Comment by matrosovas** [comment]
@dimagoltsman forgot to mention you when creating this :) Thanks for your time.

**Comment by dimagoltsman** [comment]
actually i have no idea :( never used any bridge, i only use home assistant

**Comment by amatrosovas** [comment]
@dimagoltsman seems to work, is there a bigger list of valid remote IDs I cannot seem to guess any.

**Comment by dimagoltsman** [comment]
i think this two will work 8500, 19303
also, try numbers that have odd number of ones in the binary representation
