### ISSUE TITLE
RF latched suggestion

### ISSUE THREAD

**Issue by ElGranLoky** [dimagoltsman/Random-Broadlink-RM-Code-Generator#5]
Good morning, I wonder if it is possible to add an option in the generation of the code, I mean.

When a random code is generated, the generation of a code for latched could be enabled.

In this way, for sensors that only learn one code, it is possible to generate a shutdown code and a power code, instead of using a code to turn on or off in mode switch, that if the sending of the command is not correct we do not know if the receiver is off or on, in this way we can guarantee the status sent again the command if necessary.

It could work for fixed codecs like pt2262 or pt2264 for example

Greeting

**Comment by dimagoltsman** [comment]
it depends on the switch
