### ISSUE TITLE
Add LightwaveRF code generation?

### ISSUE THREAD

**Issue by derekoharrow** [dimagoltsman/Random-Broadlink-RM-Code-Generator#7]
Any chance of adding LightwaveRF switch code generation to this - similar to how you have done Livolo?

There is a great write-up of the protocol here - https://github.com/roberttidey/LightwaveRF/blob/master/LightwaveRF433.pdf

This would then enable people to generate codes to setup Lightwave devices with Broadlink, without requiring the Lightwave Link or a remote.

Thanks

**Comment by jperquin** [comment]
Additionally a code generator for popular bofu / zemismart rollerblind motors would be handy. They use the BF-301 series RF remotes. The protocol was reverse engineered by Antti Kirjavainen for the same "Markisol" branded version. See [here](https://github.com/akirjavainen/markisol/blob/master/Markisol.ino)

**Comment by dimagoltsman** [comment]
its better someone who has it to PR. i dont have this switches
