### ISSUE TITLE
How to send command trough Broadlink RM4 Pro

### ISSUE THREAD

**Issue by djcrawleravp** [dimagoltsman/Random-Broadlink-RM-Code-Generator#9]
First of all thank you very much for this generator, I've been looking everywhere for my RF plug remote controller but no luck.

My goal first is to send the random generated command into my RF switch in learning mode (as i lost the original remote), and then using the same command to trigger the device but for some reason the service in homeassistant is not working

Am I doing somethin wrong?

Thanks in advance

<img width="1476" alt="Screen Shot 2023-03-06 at 19 59 11" src="https://user-images.githubusercontent.com/12896341/223284005-e16e0444-7457-4c57-bba7-5a628eb7c692.png">

**Comment by dimagoltsman** [comment]
Try adding `b64:` before the code
